---
# Take this example data set to build up your own!


# Use this variables to limit the drawn books to a certain range
#from: 2021-01-01
#to: 2022-12-31

categories:
  - id: ensayo
    name: Ensayo
    color: '#ff5555'

  - id: narrativa
    name: Narrativa
    color: '#2a7fff'

  - id: romance
    name: Romance
    color: '#ff1694'

  - id: thriller
    name: Suspense
    color: '#ffd801'

  - id: misc
    name: Miscelánea
    color: '#50fa7b'

books:

  - title: Pues no se te nota
    author: Bea Sánchez
    started: 2025-02-17
    finished: 2025-03-09
    publication_year: 2025
    score: 7
    category: ensayo

  - title: Vera, una historia de amor
    author: Juan del Val
    started: 2025-11-16
    finished: 2025-11-19
    publication_year: 2025
    score: 7
    category: romance

  - title: El brillo de las luciérnagas
    author: Paul Pen
    started: 2025-10-02
    finished: 2025-10-16
    publication_year: 2013
    score: 6
    category: thriller

  - title: La niña salvaje
    author: Kristin Hannah
    started: 2025-04-15
    finished: 2025-05-05
    publication_year: 2025
    score: 9
    category: thriller

  - title: Love, theoretically
    author: Ali Hazelwood
    started: 2025-05-17
    finished: 2025-06-10
    publication_year: 2023
    score: 8
    category: romance

  - title: La chica de Woodstock
    author: Elena Castillo
    started: 2025-06-12
    finished: 2025-07-08
    publication_year: 2025
    score: 9
    category: fantasy

  - title: Mi concepción del mundo
    author: Erwin Schrödinger
    started: 2025-09-24
    finished: 2025-10-01
    publication_year: 1962
    score: 5
    category: ensayo

  - title: Mente y materia
    author: Erwin Schrödinger
    started: 2025-05-05
    finished: 2025-06-12
    publication_year: 1956
    score: 7
    category: ensayo

  - title: ¿Qué es la vida?
    author: Erwin Schrödinger
    started: 2025-03-19
    finished: 2025-03-21
    publication_year: 1944
    score: 9
    category: ensayo

  - title: Crisálida
    author: Fernando Navarro
    started: 2025-09-04
    finished: 2025-09-18
    publication_year: 2025
    score: 9
    category: thriller

  - title: The blind spot
    author: Adam Frank
    started: 2024-10-04
    finished: 2025-09-23
    publication_year: 2024
    score: 5
    category: ensayo

  - title: La importancia de tu nombre
    author: Clara Peñalver
    started: 2025-02-28
    finished: 2025-03-12
    publication_year: 2022
    score: 9
    category: thriller

  - title: La luz de Granada
    author: Fex Maldonado
    started: 2025-05-22
    finished: 2025-06-07
    publication_year: 2023
    score: 9
    category: narrativa

  - title: El libro de los 5 anillos
    author: Myamoto Musashi
    started: 2025-08-05
    finished: 2025-08-06
    publication_year: 1645
    score: 6
    category: misc

  - title: The denial of death
    author: Ernest Becker
    started: 2025-07-28
    finished: 2025-08-09
    publication_year: 1973
    score: 5
    category: ensayo

  - title: The summer that melted everything
    author: Tiffany McDaniel
    started: 2025-03-26
    finished: 2025-04-08
    publication_year: 2016
    score: 8
    category: narrativa

  - title: The humans
    author: Matt Haig
    started: 2025-03-13
    finished: 2025-04-02
    publication_year: 2013
    score: 10
    category: narrativa

  - title: La última sultana
    author: Andrea D. Morales
    started: 2025-08-09
    finished: 2025-09-02
    publication_year: 2022
    score: 8
    category: narrativa

  - title: Never split the difference
    author: Chris Voss
    started: 2025-11-04
    finished: 2025-11-11
    publication_year: 2016
    score: 10
    category: ensayo

  - title: Siddhartha
    author: Hermann Hesse
    started: 2025-03-07
    finished: 2025-03-08
    publication_year: 1922
    score: 8
    category: misc
